"""create devices and interfaces

Revision ID: 08284901c65a
Revises: 
Create Date: 2026-10-05 12:13:23.641709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08284901c65a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('device_type', sa.Enum('SERVER', 'SWITCH', 'PDU', 'STORAGE', name='devicetype'), nullable=False),
    sa.Column('rack', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'PROVISIONING', 'ACTIVE', 'MAINTENANCE', 'DECOMMISSIONED', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_serial'), 'devices', ['serial'], unique=True)
    op.create_table('interfaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_device_id'), 'interfaces', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interfaces_device_id'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_devices_serial'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
